#### Problem Statemnt:
Given an integer array of size 10. Replace the odd number in numpy array with -1 ?

*Note*: Generate the following array
```
array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
```
Print the Numpy array.

#### Output Format :
```
firstElement secondElement  ... 
```

In [1]:
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [11]:
# Option 1
import numpy as np
nparr=np.array(arr)
res=np.where(nparr%2!=0)
for i in res:
    nparr[i]=-1
print(nparr)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [13]:
# Option 2
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
import numpy as np
nparr=np.array(arr)
nparr[nparr%2!=0]=-1
for i in nparr:
    print(i, end=" ")

-1 2 -1 4 -1 6 -1 8 -1 10 

In [1]:
import numpy as np
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
arr = np.array(arr)
arr[np.where((arr%2)!=0)]=-1
arr

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])