#### Problem Statemnt:
Sort a given 2D array of shape (4, 5) by 2nd column (i.e. column at index 1) in ascending order.
That means, we should re-arrange complete row based on 2nd columns' values.

Given 2D array is:
```
 [[21 20 19 18 17]
 [16 15 14 13 12]
 [11 10  9  8  7]
 [ 6  5  4  3  2]]
```
Print the 2D array in sorted order.

*Note* you have to generate the 2D Array.Here 2nd column means column present at index 1.

#### Output Format :
```
[[ 6  5  4  3  2]
[11 10  9  8  7]
[16 15 14 13 12]
[21 20 19 18 17]]
```

In [37]:
import numpy as np
arr = np.array( [[21,20,19,18,17],[16,15,14,13,12],[11,10,9,8,7],[6,5,4,3,2]])
index=np.argsort(arr[:,1])
index
arr[index]

array([[ 6,  5,  4,  3,  2],
       [11, 10,  9,  8,  7],
       [16, 15, 14, 13, 12],
       [21, 20, 19, 18, 17]])

In [23]:
import numpy as np

# Generate the 2D array
array = np.array([[21, 20, 19, 18, 17],
                  [16, 15, 14, 13, 12],
                  [11, 10, 9, 8, 7],
                  [6, 5, 4, 3, 2]])

# Get the indices that would sort the array along the 2nd column
sort_indices = np.argsort(array[:, 1])

# Rearrange the rows of the array based on the sort indices
sorted_array = array[sort_indices]

# Print the sorted 2D array
print(sorted_array)

[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]
