#### Problem Statement:

Create a matrix having diagonal elements as 1 and all other elements as 0 of size (5, 6). Print the Numpy array.

#### Output Format: 
```
numpyArray
```

In [4]:
import numpy as np
a=np.eye(5,6)
print(a)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]
