- np.array()
- np.ones()
- np.zeros()
- np.empty()
- np.full()

In [37]:
import numpy as np
a=[1,2,3,4]
b=np.array(a)
print(b)
type(b)

[1 2 3 4]


numpy.ndarray

In [38]:
import numpy as np
a=[1,2,3,4,'a','b']
b=np.array(a)
print(b)
type(b)

['1' '2' '3' '4' 'a' 'b']


numpy.ndarray

In [39]:
# char '6.6' cannot be converted to int but char '6.6' can be converted to float
import numpy as np
a=[1,2,3,4,'5','6',7.1]
b=np.array(a, dtype=int)
print(b)
type(b)

[1 2 3 4 5 6 7]


numpy.ndarray

In [40]:
# char '6.6' cannot be converted to int but char '6.6' can be converted to float
import numpy as np
a=[1,2,3,4,'5','6.6',7.1]
b=np.array(a, dtype=float)
print(b)
type(b)

[1.  2.  3.  4.  5.  6.6 7.1]


numpy.ndarray

In [41]:
import numpy as np
a=[1,2,3,4,'5','6.6',7.1, 'a']
b=np.array(a, dtype=str)
print(b)
type(b)

['1' '2' '3' '4' '5' '6.6' '7.1' 'a']


numpy.ndarray

In [42]:
# create 3 times duplicate array

import numpy as np
a=[1,2,3,4,'5','6.6',7.1, 'a']
b=np.array(a*3, dtype=str)
print(b)
type(b)

['1' '2' '3' '4' '5' '6.6' '7.1' 'a' '1' '2' '3' '4' '5' '6.6' '7.1' 'a'
 '1' '2' '3' '4' '5' '6.6' '7.1' 'a']


numpy.ndarray

In [43]:
# Example of np.ones() by default it gives float 1s 
import numpy as np
a = np.ones(3)
print(a)
type(a)

b = np.ones(3, dtype= int)
print(b)
type(b)

[1. 1. 1.]
[1 1 1]


numpy.ndarray

In [44]:
import numpy as np
a=np.zeros(3)
print(a)
b=np.zeros(3, dtype=int)
print(b)


[0. 0. 0.]
[0 0 0]


In [45]:
# Creating 2D array
import numpy as np
a=np.zeros((3,4))
print(a)
b=np.zeros((3,4), dtype=int)
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [46]:
import numpy as np
a=np.full(3,4)
print(a)
b=np.full((3,4),5)
print(b)
c=np.full((3,4),6, dtype=float)
print(c)


[4 4 4]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]]


In [55]:
# numpy.empty(shape, dtype = float, order = ‘C’) : Return a new array of given shape and type, with random values.
# Referece: https://www.geeksforgeeks.org/numpy-empty-python/
import numpy as np
a=np.empty(2)
print(a)
b=np.empty([2,2])
print(b)
c=np.empty([2,2], dtype=int)
print(c)

[2.05833592e-312 2.33419537e-312]
[[0.00000000e+000 5.21501879e-310]
 [5.21501879e-310 5.21501879e-310]]
[[              0 105553155326118]
 [105553155359920 105553155359824]]
