In [21]:
import numpy as np
arr=np.random.randint(1,30,(6,5))
arr

array([[20, 19, 17, 26, 14],
       [18, 20, 20, 16, 12],
       [ 1, 28, 29, 15, 16],
       [18, 12, 14, 18,  6],
       [29, 21,  8,  8, 10],
       [13, 26, 19,  2,  1]])

In [22]:
bool_arr=arr>20

In [23]:
arr[bool_arr]=100

In [24]:
arr

array([[ 20,  19,  17, 100,  14],
       [ 18,  20,  20,  16,  12],
       [  1, 100, 100,  15,  16],
       [ 18,  12,  14,  18,   6],
       [100, 100,   8,   8,  10],
       [ 13, 100,  19,   2,   1]])

In [25]:
bool_arr=arr[:,3] == 100

In [26]:
bool_arr

array([ True, False, False, False, False, False])

In [27]:
arr[bool_arr,3]=95

In [28]:
arr

array([[ 20,  19,  17,  95,  14],
       [ 18,  20,  20,  16,  12],
       [  1, 100, 100,  15,  16],
       [ 18,  12,  14,  18,   6],
       [100, 100,   8,   8,  10],
       [ 13, 100,  19,   2,   1]])