#### Problem Statement:
Given a 2D integer array size (4, 5) with name input_?

Print elements of highlighted matrix

In [1]:
arr=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]

In [3]:
import numpy as np
nparr1=np.array(arr)
nparr1[2,:3]

array([11, 12, 13])

In [5]:
import numpy as np
nparr1=np.array(arr)
nparr1[1:4,3]

array([ 9, 14, 19])

In [6]:
import numpy as np
nparr1=np.array(arr)
nparr1[2:4]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [7]:
import numpy as np
nparr1=np.array(arr)
nparr1[1:3,1:3]

array([[ 7,  8],
       [12, 13]])

In [33]:
import numpy as np
nparr1=np.array(arr)
temp=[]
temp=nparr1[2,:3]
for i in temp:
    print(i,end=" ")
print()
temp=nparr1[1:4,3]
for i in temp:
    print(i,end=" ")
print()
temp=nparr1[2:4]
for i in range(len(temp)):
    for j in range(len(temp[0])):
        print(temp[i][j],end=" ")
print()
temp=nparr1[1:3,1:3]
for i in range(len(temp)):
    for j in range(len(temp[0])):
        print(temp[i][j],end=" ")
print()

11 12 13 
9 14 19 
11 12 13 14 15 16 17 18 19 20 
7 8 12 13 
